import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Home.module.css';

import Banner from '../components/Banner';
import Card from '../components/Card';

import { fetchRestaurantData } from '../lib/restaurant_api';

export async function getStaticProps() {
  const coffeeStores = await fetchRestaurantData();

  return {
    props: {
      coffeeStores,
    },
  };
}

export default function Home({ coffeeStores }) {
  console.log(coffeeStores);
  const bannerBtnClickHandler = () => {
    console.log('Hi, button was clicked');
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Sandwich Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Banner
          buttonText={'View shops nearby'}
          onBannerBtnClick={bannerBtnClickHandler}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/cloud_1.png"
            width={300}
            height={115}
            alt="A happy little cloud"
          />
        </div>
        {coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Dover Sandwich Shops</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((store) => (
                <Card
                  key={store.id}
                  id={store.id}
                  name={store.name}
                  href={`/coffee-store/${store.id}`}
                  imgUrl={store.imgUrl}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
